insert into Utilisateur(id,actif,email,login,nbConges,nbRTT,nom,prenom,quatrevingt,role,version,deltaJoursConges,deltaJoursRTT) values(1,1,'jroynette@gmail.com','user1',10,10,'nom','prenom',1,0,1,0,0)
insert into Utilisateur(id,actif,email,login,nbConges,nbRTT,nom,prenom,quatrevingt,role,version,deltaJoursConges,deltaJoursRTT) values(2,1,'jroynette@gmail.com','user2',10,10,'nom2','prenom2',1,1,1,0,0)
insert into Projet(id,annee,nom,description,version) values (1,2012,'test','desc',1)
insert into Projet(id,annee,nom,description,version) values (2,2012,'test1','desc1',1)
insert into Projet(id,annee,nom,description,version) values (3,2012,'test2','desc2',1)
insert into Projet(id,annee,nom,description,version) values (4,2012,'test3','desc3',1)
insert into Absence(id,commentaire,dateDebut,dateFin,debutPM,finAM,statut,type,utilisateur_id) values (1,'',PARSEDATETIME('2012-03-13','yyyy-MM-d'),PARSEDATETIME('2012-03-13','yyyy-MM-d'),0,0,1,1,2)
insert into Absence(id,commentaire,dateDebut,dateFin,debutPM,finAM,statut,type,utilisateur_id) values (2,'',PARSEDATETIME('2012-03-22','yyyy-MM-d'),PARSEDATETIME('2012-03-22','yyyy-MM-d'),0,0,0,1,2)
insert into SaisieTemps(id,commentaire,date,heures,projet_id,utilisateur_id) values (1,'',PARSEDATETIME('2012-03-13','yyyy-MM-d'),1,1,2)
insert into SaisieTemps(id,commentaire,date,heures,projet_id,utilisateur_id) values (2,'',PARSEDATETIME('2012-03-15','yyyy-MM-d'),2,2,2)
insert into SaisieTemps(id,commentaire,date,heures,projet_id,utilisateur_id) values (3,'',PARSEDATETIME('2012-03-16','yyyy-MM-d'),3,3,2)
insert into SaisieTemps(id,commentaire,date,heures,projet_id,utilisateur_id) values (4,'téest',PARSEDATETIME('2012-03-17','yyyy-MM-d'),4,4,2)
insert into DejeunerExterne(id,date,utilisateur_id) values (1,PARSEDATETIME('2012-03-18','yyyy-MM-d'),2)
