// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.appa.planning.bo;

import org.appa.planning.bo.ProjetDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProjetIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProjetIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProjetIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ProjetIntegrationTest: @Transactional;
    
    @Autowired
    private ProjetDataOnDemand ProjetIntegrationTest.dod;
    
    @Test
    public void ProjetIntegrationTest.testCountProjets() {
        org.junit.Assert.assertNotNull("Data on demand for 'Projet' failed to initialize correctly", dod.getRandomProjet());
        long count = org.appa.planning.bo.Projet.countProjets();
        org.junit.Assert.assertTrue("Counter for 'Projet' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProjetIntegrationTest.testFindProjet() {
        org.appa.planning.bo.Projet obj = dod.getRandomProjet();
        org.junit.Assert.assertNotNull("Data on demand for 'Projet' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Projet' failed to provide an identifier", id);
        obj = org.appa.planning.bo.Projet.findProjet(id);
        org.junit.Assert.assertNotNull("Find method for 'Projet' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Projet' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProjetIntegrationTest.testFindAllProjets() {
        org.junit.Assert.assertNotNull("Data on demand for 'Projet' failed to initialize correctly", dod.getRandomProjet());
        long count = org.appa.planning.bo.Projet.countProjets();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Projet', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.appa.planning.bo.Projet> result = org.appa.planning.bo.Projet.findAllProjets();
        org.junit.Assert.assertNotNull("Find all method for 'Projet' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Projet' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProjetIntegrationTest.testFindProjetEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Projet' failed to initialize correctly", dod.getRandomProjet());
        long count = org.appa.planning.bo.Projet.countProjets();
        if (count > 20) count = 20;
        java.util.List<org.appa.planning.bo.Projet> result = org.appa.planning.bo.Projet.findProjetEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Projet' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Projet' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProjetIntegrationTest.testFlush() {
        org.appa.planning.bo.Projet obj = dod.getRandomProjet();
        org.junit.Assert.assertNotNull("Data on demand for 'Projet' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Projet' failed to provide an identifier", id);
        obj = org.appa.planning.bo.Projet.findProjet(id);
        org.junit.Assert.assertNotNull("Find method for 'Projet' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProjet(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Projet' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProjetIntegrationTest.testMerge() {
        org.appa.planning.bo.Projet obj = dod.getRandomProjet();
        org.junit.Assert.assertNotNull("Data on demand for 'Projet' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Projet' failed to provide an identifier", id);
        obj = org.appa.planning.bo.Projet.findProjet(id);
        boolean modified =  dod.modifyProjet(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.appa.planning.bo.Projet merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Projet' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProjetIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Projet' failed to initialize correctly", dod.getRandomProjet());
        org.appa.planning.bo.Projet obj = dod.getNewTransientProjet(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Projet' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Projet' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Projet' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProjetIntegrationTest.testRemove() {
        org.appa.planning.bo.Projet obj = dod.getRandomProjet();
        org.junit.Assert.assertNotNull("Data on demand for 'Projet' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Projet' failed to provide an identifier", id);
        obj = org.appa.planning.bo.Projet.findProjet(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Projet' with identifier '" + id + "'", org.appa.planning.bo.Projet.findProjet(id));
    }
    
}
