// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.appa.planning.bo;

import java.lang.String;

privileged aspect Site_Roo_JavaBean {
    
    public String Site.getNom() {
        return this.nom;
    }
    
    public void Site.setNom(String nom) {
        this.nom = nom;
    }
    
}
