drop table Absence if exists
drop table Projet if exists
drop table SaisieTemps if exists
drop table Utilisateur if exists
create table Absence (id bigint generated by default as identity (start with 1), dateDebut timestamp not null, dateFin timestamp not null, statut integer not null, type integer not null, utilisateur_id bigint, primary key (id))
create table Projet (id bigint generated by default as identity (start with 1), annee integer not null, nom varchar(30) not null, primary key (id))
create table SaisieTemps (id bigint generated by default as identity (start with 1), commentaire varchar(100), date timestamp not null, dejExterne bit, periode integer not null, temps integer, projet_id bigint not null, utilisateur_id bigint not null, primary key (id))
create table Utilisateur (id bigint generated by default as identity (start with 1), actif bit not null, login varchar(20) not null, nbConges integer not null, nbRTT integer not null, nom varchar(30) not null, prenom varchar(30) not null, quatrevingt bit not null, role varchar(10) not null, primary key (id), unique (login))
alter table Absence add constraint FK1C341A1D40393A86 foreign key (utilisateur_id) references Utilisateur
alter table SaisieTemps add constraint FKB3C98C4B184DF70E foreign key (projet_id) references Projet
alter table SaisieTemps add constraint FKB3C98C4B40393A86 foreign key (utilisateur_id) references Utilisateur
